### ISSUE TITLE
有用react native吗?

### ISSUE THREAD

**Issue by alihanniba** [lizwangying/lizwangying.github.io#2]
有用react native吗?

**Comment by lizwangying** [comment]
哈哈，木有。考虑有空去学吧，先得学js不是么？

**Comment by alihanniba** [comment]
那js学得咋样了啊

**Comment by lizwangying** [comment]
基础学完了，得找点东西做练手才行。

**Comment by lizwangying** [comment]
谢谢关心啊~最近一直加班，没时间去学东西。真是心累~你博客页脚的微信并没有链接啊~哈哈，还想加你希望你指点我js呢、

**Comment by alihanniba** [comment]
.....刚刚看了下....有啊.....都好久没管那个了....

**Comment by lizwangying** [comment]
哦，浏览器问题，360无反应~快去解决bug。
今天闲了，看kotlin。真是时间多了不知道该学啥。
